### ISSUE TITLE
Need documentation on some missing styles after migration (1.6.5 => 2.0.0)

### ISSUE THREAD

**Issue by bbougot** [MahApps/mahapps.com#3]
I'm migrating my .NET 4.7.2 WPF application using MahApps.Metro 1.6.5 to .NET Core 3.0 using MahApp.Metro 2.0.0-alpha0531 and some of my styles that were working fine simply break at runtime with the newest version.

- `MetroListBox` style is not referenced anymore thus break the styling of my ListBox.
- The same goes for `MetroListBoxItem`.
- `AccentedSquareButtonStyle` style does not exist anymore and break the styling of my Buttons.
- `SearchMetroTextBox` style does not exist anymore and break the styling of my TextBox.

I've carefullly watched the documentation and searched for those missing styles but couldn't find any equivalent/migration guide for these particular components.

**Comment by punker76** [comment]
@bbougot @superlloyd The migration guide can be found here https://mahapps.com/docs/guides/migration-to-v2.0

@Gerardo-Sista Here is the full converted style:

```xaml
<Style BasedOn="{StaticResource MahApps.Styles.TextBox}" TargetType="{x:Type TextBox}">
    <Setter Property="FontSize" Value="20"/>
    <Setter Property="FontFamily" Value="Consolas"/>
    <Setter Property="FontWeight" Value="Bold"/>
    <Setter Property="TextWrapping" Value="Wrap"/>
    <Setter Property="MinWidth" Value="50"/>
    <Setter Property="BorderBrush" Value="{DynamicResource MahApps.Brushes.AccentBase}"/>
    <Setter Property="mah:TextBoxHelper.ClearTextButton" Value="True"/>
    <Setter Property="mah:TextBoxHelper.UseFloatingWatermark" Value="True"/>
    <Setter Property="mah:TextBoxHelper.SelectAllOnFocus" Value="True"/>
    <Setter Property="val:ValidationsHelper.Property" Value="Text"/>
    <Style.Triggers>
        <Trigger Property="Validation.HasError" Value="True">
            <Setter Property="ToolTip" Value="{Binding RelativeSource={RelativeSource Self}, Path=(Validation.Errors)[0].ErrorContent}"/>
        </Trigger>
    </Style.Triggers>
</Style>
```

@paatrickd Here are the links for the ThemeManager stuff:

- https://mahapps.com/docs/themes/usage
- https://mahapps.com/docs/themes/thememanager
- https://github.com/ControlzEx/ControlzEx/blob/develop/Wiki/ThemeManager.md
