### ISSUE TITLE
GlowBrush="{DynamicResource AccentColorBrush}" Unresolved

### ISSUE THREAD

**Issue by luky1374** [MahApps/mahapps.com#5]
I followed the [Mahapps Quick start guide ](https://mahapps.com/guides/quick-start.html) to code my first Mahapps.Metro WPF application. Using v2.0.0 alpha. 

`<Controls:MetroWindow x:Class="MahAppsMetroSample.MainWindow"
                      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                      xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
                      xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
                      Title="DeepSense"
                      GlowBrush="{DynamicResource AccentColorBrush}"
                      WindowStartupLocation="CenterScreen">

    <Controls:MetroWindow.RightWindowCommands>
        <Controls:WindowCommands>
            <Button Content="settings" />
            <Button>
                <StackPanel Orientation="Horizontal">
                    <iconPacks:PackIconModern Width="24" Height="24" Kind="FoodCupcake" />
                    <TextBlock Margin="4 0 0 0" VerticalAlignment="Center" Text="deploy cupcakes" />
                </StackPanel>
            </Button>
        </Controls:WindowCommands>
    </Controls:MetroWindow.RightWindowCommands>

    <Grid>
    </Grid>

</Controls:MetroWindow>`

The GlowBrush="{DynamicResource AccentColorBrush}" seems unresolved. Is there any reference I have skipped? Unable to troubleshoot,  help is appreciated.

Thanks

**Comment by punker76** [comment]
The guide can be found here https://mahapps.com/docs/guides/migration-to-v2.0
