### ISSUE TITLE
A small error in the document 

### ISSUE THREAD

**Issue by LuGuangguang** [MahApps/mahapps.com#7]
Page of the Support MVVM with the DialogCoordinator
![图片](https://user-images.githubusercontent.com/34500722/82869513-f8ea4180-9f60-11ea-934a-bb98a330cdf4.png)

Constructer Name is wrong

**Comment by shiftkey** [comment]
@LuGuangguang if you wanted to contribute a fix, this is the source file to change: https://github.com/MahApps/mahapps.com/blob/master/input/docs/controls/dialogs.md
